services: 
  mysqldb:
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ventas_db 
    ports:
      - "3307:3306"
    networks:
      - app_net
    volumes:
      - mysql-vol:/var/lib/mysql

  backend:
    depends_on:
        - mysqldb
    restart: on-failure
    container_name: backend
    image: carlosmz87/p1_bases1_backend
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app_net
    links:
      - mysqldb
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=mysqldb
      - DATABASE_NAME=ventas_db
      - DATABASE_PORT=3306

networks:
  app_net:
    driver: bridge

volumes:
  mysql-vol: 


