FROM node:18.7.0

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app
# If you are building your code for production
# RUN npm ci --only=production

EXPOSE 3000
CMD [ "node", "index.js" ]